# 应用名称
server:
  port: 9001

dubbo:
  application:
    name: springboot-dubbo-provider
  registry:
    address: zookeeper://101.35.19.88:2180,101.35.19.88:2181,101.35.19.88:2182
  #    name: rest
  # 通信协议名称
  #name: dubbo
  # 协议端口
  #port: 20882
  #    port: 8083
  #  scan:
  #    base-packages: com.example.springboot.dubbo.provider # 可以不用再使用@EnableDubbo注解
  protocols:
    protocol1:
      id: dubbo1
      name: dubbo
      port: 20881
      #      host: 0.0.0.0
      # REST协议默认选用Jetty Servlet容器,默认采用长连接
      #      server: tomcat
      # 类似Java Web中的context path
      #      contextpath: /api
      #      threads: 100
      # 定义客户端调用此REST服务的最大超时时间
    #      timeout: 2000
    #      connections: 10
    protocol2:
      id: dubbo2
      name: dubbo
      port: 20882
    #      host: 0.0.0.0
    protocol3:
      id: dubbo3
      name: dubbo
      port: 20883
#      host: 0.0.0.0



