spring:
  application:
    name: springcloud-transaction
  datasource:
    username: william
    password: Monday01
    url: jdbc:mysql://139.196.113.146:3306/op_sp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最大连接池数量
      max-active: 30
      # 最小连接池数量
      min-idle: 5
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计;wall防止sql注入
      # FilterChain 责任链模式
      filters: stat,wall
      filter:
        stat:
          enabled: true
          # 慢查询
          slow-sql-millis: 500
          # 打开mergeSql功能
          merge-sql: true
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 连接池监控
      stat-view-servlet:
        enabled: true
        login-username: huajinsc
        login-password: admin
        url-pattern: /druid/*
        # ip白名单
        allow:
        # 黑名单(共同存在时，deny高于allow)
        deny:
      web-stat-filter:
        enabled: true
        url-pattern: /*

# 端口号
server:
  port: 10340

logging:
  level:
    root: info
  file:
    path:
  # 日志配置文件
  config: classpath:logback.xml


# eureka注册中心服务的配置
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://10.241.25.222:10002/eureka
