# 应用名称
spring:
  application:
    name: springcloud-openfeign-example

server:
  port: 8000

logging:
  level:
    # 指定那个FeignClient接口的请求需要输出日志，以及日志级别
    com.example.springcloud.openfeign.service.GitHubService: info

feign:
  # org.springframework.cloud.openfeign.clientconfig.HttpClientFeignConfiguration
  httpclient:
    enabled: true
    connection-timeout: 2000
    max-connections: 200
  hystrix:
    enabled: true
  # 压缩配置
  compression:
    request:
      enabled: true
      # 配置压缩支持的MIME TYpe
      mime-types: text/xml,application/xml,application/json
      # 配置压缩数据大小的下限
      min-request-size: 2048
    response:
      # 配置响应GZIP压缩
      enabled: true
  client:
    config:
      # 需要配置的FeignName
      github-client:
        # 连接超时时间
        connectTimout: 5000
        # 读超时时间
        readTimeut: 5000
        # Feign的日志级别
        loggerLevel: full


ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 5000

# 设置hystrix超时时间
hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowinMilliseconds: 10000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutinMilliseconds: 10000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  #eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
  #如果不配置,会将当前服务提供者所在的主机名注册到Eureka Server上。
  instance:
    prefer-ip-address: true






