spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: springcloud-example
  redis:
    database: 0
    password: Monday01
    cluster:
      max-redirects: 3
      nodes:
        - 139.196.113.146:6380
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 2
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000ms
    timeout: 5000ms
# 端口号
server:
  port: 10352

logging:
  level:
    root: info
  file:
    path:
  # 日志配置文件
  config: classpath:logback.xml


# eureka注册中心服务的配置
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://10.241.25.222:10002/eureka



# Zookeeper配置
zookeeper:
  address: 139.196.113.146:2181,139.196.113.146:2182,139.196.113.146:2183
  retryCount: 5               #重试次数
  elapsedTimeInMs: 5000         #重试间隔时间
  sessionTimeoutInMs: 30000     #Session超时时间
  connectionTimeoutInMs: 10000  #连接超时时间
